#!/usr/bin/env python3
"""Column generation for the three anchored-stabilizer cubic SOS blocks.

For one representative ``v`` of each cell orbit, let ``H_v`` be its
stabilizer in the 2,304-element automorphism group of the two-zero face.
The cubic monomials have respectively 117, 440, and 272 orbits under these
three stabilizers.  If ``p_v`` is the vector of corresponding orbit sums,
this script searches the cone generated by

    sum_{gamma in Gamma/H_v} p_v(gamma x)^T Q_v p_v(gamma x),  Q_v >= 0.

Rather than construct the full 141,051-coordinate coefficient map, the
script solves a master LP over rank-one Gram rays.  It prices each complete
PSD block by compressing the full cubic dual slack matrix to the relevant
stabilizer-fixed subspace.  A negative generalized eigenvector is exactly a
missing rank-one ray from that anchored block.

This is numerical discovery code, not a proof verifier.  Every iteration is
checkpointed, including negative-margin runs.  A positive result would still
need exact rounding and independent verification.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
from scipy import optimize, sparse

import search_cubic_column_n6 as cubic
import search_cubic_obstruction_rays_n6 as cubic_rays
import search_degree4_column_n6 as degree4
import search_pair_sos_n6 as linear
import search_sos_n6 as base


EXPECTED_FEATURE_COUNTS = (117, 440, 272)


def anchored_features(
    group: np.ndarray,
) -> tuple[np.ndarray, list[sparse.csr_array], list[np.ndarray]]:
    """Return anchor representatives, orbit-sum maps, and feature sizes."""
    anchors = np.asarray(base.vertex_representatives(group), dtype=np.int16)
    cubic_count = base.multiset_count(3)
    maps: list[sparse.csr_array] = []
    sizes: list[np.ndarray] = []
    actual_counts = []
    for anchor in anchors:
        stabilizer = group[group[:, int(anchor)] == int(anchor)]
        feature_ids, representatives, feature_sizes = base.monomial_orbits(
            3, stabilizer
        )
        feature_count = len(representatives)
        actual_counts.append(feature_count)
        orbit_sum_map = sparse.coo_array(
            (
                np.ones(cubic_count, dtype=float),
                (
                    np.arange(cubic_count, dtype=np.int32),
                    feature_ids,
                ),
            ),
            shape=(cubic_count, feature_count),
        ).tocsr()
        maps.append(orbit_sum_map)
        sizes.append(feature_sizes.astype(float))
    if tuple(actual_counts) != EXPECTED_FEATURE_COUNTS:
        raise AssertionError(f"unexpected anchored feature counts {actual_counts}")
    return anchors, maps, sizes


def fixed_degree_four_rays(
    seed_path: Path,
    group: np.ndarray,
    degree_six_orbits: np.ndarray,
    degree_six_sizes: np.ndarray,
) -> tuple[list[np.ndarray], np.ndarray, np.ndarray]:
    """Project a prior degree-four result and retain one ray per nonzero block."""
    seed = np.load(seed_path, allow_pickle=False)
    multipliers = np.asarray(seed["multipliers"], dtype=np.int16)
    coordinates = np.asarray(seed["gram_coordinates"], dtype=float)
    lookup = {
        (int(i), int(j)): index
        for index, (i, j) in enumerate(linear.LINEAR_UPPER)
    }
    full_index = np.asarray(
        [
            [lookup[tuple(sorted((i, j)))] for j in range(base.NV)]
            for i in range(base.NV)
        ]
    )
    columns = []
    retained_multipliers = []
    retained_grams = []
    for multiplier, gram in zip(multipliers, coordinates[:, full_index]):
        eigenvalues, eigenvectors = np.linalg.eigh((gram + gram.T) / 2)
        projected = (eigenvectors * np.maximum(eigenvalues, 0)) @ eigenvectors.T
        trace = float(np.trace(projected))
        if trace <= 1e-14:
            continue
        normalized = projected / trace
        matrix = degree4.multiplier_matrix(
            len(group), multiplier, degree_six_orbits, degree_six_sizes
        )
        columns.append(np.asarray(matrix @ degree4.pair_vector(normalized)).ravel())
        retained_multipliers.append(multiplier)
        retained_grams.append(normalized)
    if not columns:
        raise ValueError("degree-four seed has no nonzero PSD blocks")
    return (
        columns,
        np.asarray(retained_multipliers, dtype=np.int16),
        np.asarray(retained_grams),
    )


def canonicalize(vector: np.ndarray) -> np.ndarray:
    """Normalize a cubic vector and choose a deterministic sign."""
    vector = np.asarray(vector, dtype=float)
    norm = float(np.linalg.norm(vector))
    if norm <= 1e-14:
        raise ValueError("zero cubic ray")
    result = vector / norm
    pivot = int(np.argmax(np.abs(result)))
    if result[pivot] < 0:
        result = -result
    return result


def fingerprint(vector: np.ndarray) -> bytes:
    return np.round(canonicalize(vector), decimals=10).tobytes()


def compressed_eigenvectors(
    slack: sparse.csr_array,
    orbit_sum_map: sparse.csr_array,
    feature_sizes: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Diagonalize slack on an anchored orbit-sum subspace.

    The orbit sums are orthogonal but not normalized.  Conjugating by
    ``diag(feature_sizes**-1/2)`` turns the restriction into an ordinary
    symmetric eigenproblem whose vectors lift with Euclidean norm one.
    """
    compressed = np.asarray((orbit_sum_map.T @ slack @ orbit_sum_map).todense())
    inverse_roots = 1 / np.sqrt(feature_sizes)
    normalized = compressed * inverse_roots[:, None] * inverse_roots[None, :]
    normalized = (normalized + normalized.T) / 2
    eigenvalues, eigenvectors = np.linalg.eigh(normalized)
    lifted = orbit_sum_map @ (inverse_roots[:, None] * eigenvectors)
    return eigenvalues, np.asarray(lifted)


def solve_master(
    columns: list[np.ndarray], target: np.ndarray
) -> tuple[optimize.OptimizeResult, np.ndarray, np.ndarray, np.ndarray]:
    coefficient = np.column_stack(columns)
    inequalities = np.column_stack((coefficient, np.ones(len(target))))
    objective = np.zeros(coefficient.shape[1] + 1)
    objective[-1] = -1
    result = optimize.linprog(
        objective,
        A_ub=inequalities,
        b_ub=target,
        bounds=[(0, None)] * coefficient.shape[1] + [(None, None)],
        method="highs-ipm",
        options={
            "primal_feasibility_tolerance": 1e-9,
            "dual_feasibility_tolerance": 1e-9,
            "ipm_optimality_tolerance": 1e-10,
        },
    )
    if not result.success:
        raise RuntimeError(result.message)
    weights = np.maximum(result.x[:-1], 0)
    residual = target - coefficient @ weights
    dual = -np.asarray(result.ineqlin.marginals)
    return result, weights, residual, dual


def save_checkpoint(
    path: Path,
    *,
    group: np.ndarray,
    anchors: np.ndarray,
    degree_four_multipliers: np.ndarray,
    degree_four_grams: np.ndarray,
    target: np.ndarray,
    cubic_blocks: list[int],
    cubic_vectors: list[np.ndarray],
    cubic_columns: list[np.ndarray],
    weights: np.ndarray,
    residual: np.ndarray,
    margin: float,
    iteration: int,
    history: list[float],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(".tmp.npz")
    np.savez_compressed(
        temporary,
        allowed=np.asarray(base.ALLOWED, dtype=np.int8),
        group=group,
        anchors=anchors,
        anchored_feature_counts=np.asarray(EXPECTED_FEATURE_COUNTS, dtype=np.int16),
        degree_four_multipliers=degree_four_multipliers,
        degree_four_grams=degree_four_grams,
        target=target,
        cubic_blocks=np.asarray(cubic_blocks, dtype=np.int8),
        cubic_vectors=np.asarray(cubic_vectors),
        cubic_columns=np.asarray(cubic_columns),
        weights=weights,
        residual=residual,
        margin=np.asarray(margin),
        iteration=np.asarray(iteration, dtype=np.int32),
        margin_history=np.asarray(history),
    )
    temporary.replace(path)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("degree4_seed", type=Path)
    parser.add_argument("--iterations", type=int, default=30)
    parser.add_argument("--rays-per-block", type=int, default=5)
    parser.add_argument("--reduced-cost-tolerance", type=float, default=1e-9)
    parser.add_argument("--resume", type=Path)
    parser.add_argument(
        "--output", type=Path, default=Path("n6_anchored_cubic_search.npz")
    )
    args = parser.parse_args()
    if args.iterations < 1 or args.rays_per_block < 1:
        raise ValueError("iteration and ray counts must be positive")

    base.verify_ranking()
    group = base.variable_group()
    degree_six_orbits, representatives, sizes = base.monomial_orbits(6, group)
    target = base.target_coefficients(representatives)
    cubic_monomials = base.multiset_array(3)
    anchors, feature_maps, feature_sizes = anchored_features(group)
    fixed_columns, fixed_multipliers, fixed_grams = fixed_degree_four_rays(
        args.degree4_seed, group, degree_six_orbits, sizes
    )
    print(
        f"anchors={[base.ALLOWED[int(value)] for value in anchors]} "
        f"features={EXPECTED_FEATURE_COUNTS} "
        f"Gram-variables={sum(k * (k + 1) // 2 for k in EXPECTED_FEATURE_COUNTS)} "
        f"degree-four-rays={len(fixed_columns)}",
        flush=True,
    )

    cubic_blocks: list[int] = []
    cubic_vectors: list[np.ndarray] = []
    cubic_columns: list[np.ndarray] = []
    history: list[float] = []
    start = 0
    if args.resume:
        prior = np.load(args.resume, allow_pickle=False)
        if not np.array_equal(prior["allowed"], np.asarray(base.ALLOWED, dtype=np.int8)):
            raise ValueError("resume archive uses different variables")
        if not np.array_equal(prior["anchors"], anchors):
            raise ValueError("resume archive uses different anchors")
        if not np.array_equal(
            prior["degree_four_multipliers"], fixed_multipliers
        ) or not np.allclose(prior["degree_four_grams"], fixed_grams):
            raise ValueError("resume archive uses a different degree-four seed")
        cubic_blocks = [int(value) for value in prior["cubic_blocks"]]
        cubic_vectors = [canonicalize(vector) for vector in prior["cubic_vectors"]]
        if "cubic_columns" in prior.files:
            saved_columns = np.asarray(prior["cubic_columns"], dtype=float)
            if saved_columns.shape != (len(cubic_vectors), len(target)):
                raise ValueError("resume archive has malformed cubic columns")
            cubic_columns = [column for column in saved_columns]
        else:
            print("reconstructing columns from a legacy checkpoint", flush=True)
            cubic_columns = [
                cubic_rays.cubic_ray_column(
                    vector, cubic_monomials, degree_six_orbits, sizes, len(group)
                )
                for vector in cubic_vectors
            ]
        history = [float(value) for value in prior["margin_history"]]
        start = int(prior["iteration"])
        print(f"resumed iteration={start} cubic-rays={len(cubic_vectors)}", flush=True)

    seen = {fingerprint(vector) for vector in cubic_vectors}
    final_weights = np.empty(0)
    final_residual = target.copy()
    final_margin = float("-inf")
    certified_numerically = False
    for iteration in range(start + 1, start + args.iterations + 1):
        result, weights, residual, dual = solve_master(
            fixed_columns + cubic_columns, target
        )
        margin = float(result.x[-1])
        history.append(margin)
        final_weights = weights
        final_residual = residual
        final_margin = margin
        print(
            f"iteration={iteration} cubic-rays={len(cubic_vectors)} "
            f"margin={margin:.12g} residual={float(residual.min()):.12g}",
            flush=True,
        )
        if residual.min() > 1e-7 and margin > 1e-7:
            certified_numerically = True
            save_checkpoint(
                args.output,
                group=group,
                anchors=anchors,
                degree_four_multipliers=fixed_multipliers,
                degree_four_grams=fixed_grams,
                target=target,
                cubic_blocks=cubic_blocks,
                cubic_vectors=cubic_vectors,
                cubic_columns=cubic_columns,
                weights=weights,
                residual=residual,
                margin=margin,
                iteration=iteration,
                history=history,
            )
            break

        slack = cubic.cubic_dual_slack(dual, representatives, sizes, group)
        added = 0
        minima = []
        for block, (orbit_sum_map, block_sizes) in enumerate(
            zip(feature_maps, feature_sizes)
        ):
            eigenvalues, eigenvectors = compressed_eigenvectors(
                slack, orbit_sum_map, block_sizes
            )
            minima.append(float(eigenvalues[0]))
            for index in np.argsort(eigenvalues)[: args.rays_per_block]:
                if eigenvalues[index] >= -args.reduced_cost_tolerance:
                    continue
                vector = canonicalize(eigenvectors[:, int(index)])
                key = fingerprint(vector)
                if key in seen:
                    continue
                column = cubic_rays.cubic_ray_column(
                    vector, cubic_monomials, degree_six_orbits, sizes, len(group)
                )
                direct_price = float(dual @ column)
                spectral_price = float(vector @ (slack @ vector))
                if not np.isclose(direct_price, spectral_price, rtol=1e-9, atol=1e-9):
                    raise AssertionError(
                        "anchored pricing mismatch: "
                        f"coefficient={direct_price} spectral={spectral_price}"
                    )
                seen.add(key)
                cubic_blocks.append(block)
                cubic_vectors.append(vector)
                cubic_columns.append(column)
                added += 1
        print(f"  anchored minimum eigenvalues={minima} added={added}", flush=True)
        save_checkpoint(
            args.output,
            group=group,
            anchors=anchors,
            degree_four_multipliers=fixed_multipliers,
            degree_four_grams=fixed_grams,
            target=target,
            cubic_blocks=cubic_blocks,
            cubic_vectors=cubic_vectors,
            cubic_columns=cubic_columns,
            weights=weights,
            residual=residual,
            margin=margin,
            iteration=iteration,
            history=history,
        )
        if not added:
            print("anchored dual slacks are PSD before a positive margin", flush=True)
            break

    if certified_numerically:
        print("POSITIVE NUMERICAL MARGIN; exact verification still required", flush=True)
    else:
        print(
            f"NO CERTIFICATE margin={final_margin:.12g} "
            f"residual={float(final_residual.min()):.12g} "
            f"active-rays={int(np.count_nonzero(final_weights > 1e-12))}",
            flush=True,
        )
    print(args.output, flush=True)


if __name__ == "__main__":
    main()
