#!/usr/bin/env python3
"""Reduced SDP on sparse quadratic subspaces generated by hyperedge obstructions."""
from __future__ import annotations

import argparse
from pathlib import Path

import cvxpy as cp
import numpy as np
from scipy import linalg, sparse

import search_degree2_quadratic_column_n6 as quadratic
import search_degree4_column_n6 as degree4
import search_pair_sos_n6 as linear
import search_sos_n6 as base


def upper_coordinate(left: int, right: int, size: int) -> int:
    if left > right:
        left, right = right, left
    return left * size - left * (left - 1) // 2 + right - left


def independent_sparse_columns(vectors: list[np.ndarray]) -> np.ndarray:
    if not vectors:
        return np.zeros((len(base.M2), 0))
    matrix = np.column_stack(vectors)
    _, triangular, pivots = linalg.qr(matrix, mode="economic", pivoting=True)
    diagonal = np.abs(np.diag(triangular))
    rank = int(np.count_nonzero(diagonal > 1e-9))
    result = matrix[:, pivots[:rank]].copy()
    result[np.abs(result) < 1e-10] = 0
    return result


def reduced_matrix(
    original: sparse.csr_array, basis: np.ndarray
) -> tuple[sparse.csr_array, list[tuple[int, int]]]:
    """Map upper coordinates of Z to coefficients for Q = U Z U^T."""
    size = basis.shape[1]
    upper = [(i, j) for i in range(size) for j in range(i, size)]
    csc = original.tocsc()
    rows: list[int] = []
    columns: list[int] = []
    data: list[float] = []
    supports = [np.flatnonzero(basis[:, i]) for i in range(size)]
    for column, (a, b) in enumerate(upper):
        coefficients: dict[int, float] = {}
        support_a = supports[a]
        support_b = supports[b]
        if a == b:
            for position, left in enumerate(support_a):
                for right in support_a[position:]:
                    coordinate = upper_coordinate(
                        int(left), int(right), len(base.M2)
                    )
                    coefficients[coordinate] = (
                        coefficients.get(coordinate, 0.0)
                        + basis[int(left), a] * basis[int(right), a]
                    )
        else:
            for left in support_a:
                for right in support_b:
                    coordinate = upper_coordinate(
                        int(left), int(right), len(base.M2)
                    )
                    value = basis[int(left), a] * basis[int(right), b]
                    if left == right:
                        value *= 2
                    coefficients[coordinate] = coefficients.get(coordinate, 0.0) + value
        output: dict[int, float] = {}
        for coordinate, value in coefficients.items():
            start, end = csc.indptr[coordinate : coordinate + 2]
            if end - start != 1:
                raise AssertionError("unexpected multiplier-map column")
            row = int(csc.indices[start])
            output[row] = output.get(row, 0.0) + float(csc.data[start]) * value
        for row, value in output.items():
            if abs(value) > 1e-14:
                rows.append(row)
                columns.append(column)
                data.append(value)
    return (
        sparse.coo_array(
            (data, (rows, columns)),
            shape=(original.shape[0], len(upper)),
        ).tocsr(),
        upper,
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("degree4_seed", type=Path)
    parser.add_argument("--eps", type=float, default=1e-7)
    parser.add_argument("--max-iters", type=int, default=10_000)
    parser.add_argument("--direct", action="store_true")
    parser.add_argument(
        "--output", type=Path, default=Path("n6_degree2_subspace_search.npz")
    )
    args = parser.parse_args()

    group = base.variable_group()
    _, multipliers, _ = base.monomial_orbits(2, group)
    degree_six_orbits, degree_six_reps, degree_six_sizes = base.monomial_orbits(
        6, group
    )
    target = base.target_coefficients(degree_six_reps)
    matrices = [
        quadratic.multiplier_matrix(
            len(group), multiplier, degree_six_orbits, degree_six_sizes
        )
        for multiplier in multipliers
    ]

    vectors: list[list[np.ndarray]] = [[] for _ in multipliers]
    negative_rows = np.flatnonzero(target < 0)
    for row in negative_rows:
        for block, matrix in enumerate(matrices):
            slack = quadratic.sparse_slack_row(matrix, int(row))
            if slack.nnz == 0:
                continue
            eigenvalues, eigenvectors = sparse.linalg.eigsh(
                slack, k=1, which="SA", tol=1e-10
            )
            if eigenvalues[0] < -1e-9:
                vectors[block].append(eigenvectors[:, 0])
    bases = [independent_sparse_columns(block_vectors) for block_vectors in vectors]
    print("subspace dimensions", [basis.shape[1] for basis in bases], flush=True)

    reduced_matrices = []
    upper_lists = []
    z_variables = []
    z_coordinate_expressions = []
    for matrix, basis in zip(matrices, bases):
        reduced, upper = reduced_matrix(matrix, basis)
        reduced_matrices.append(reduced)
        upper_lists.append(upper)
        size = basis.shape[1]
        if size:
            variable = cp.Variable((size, size), PSD=True)
            expression = cp.hstack([variable[i, j] for i, j in upper])
        else:
            variable = None
            expression = None
        z_variables.append(variable)
        z_coordinate_expressions.append(expression)
        print(
            f"reduced block {len(reduced_matrices) - 1}: size={size} "
            f"coordinates={len(upper)} nnz={reduced.nnz}",
            flush=True,
        )

    seed = np.load(args.degree4_seed, allow_pickle=False)
    degree4_multipliers = np.asarray(seed["multipliers"], dtype=np.int16)
    coordinates = np.asarray(seed["gram_coordinates"], dtype=float)
    if degree4_multipliers.shape != (302, 4) or coordinates.shape != (
        302,
        len(linear.LINEAR_UPPER),
    ):
        raise ValueError("unexpected degree-four seed shape")
    lookup = {
        (int(i), int(j)): index
        for index, (i, j) in enumerate(linear.LINEAR_UPPER)
    }
    full_index = np.asarray(
        [
            [lookup[tuple(sorted((i, j)))] for j in range(base.NV)]
            for i in range(base.NV)
        ]
    )
    degree4_grams = []
    degree4_columns = []
    for multiplier, gram in zip(degree4_multipliers, coordinates[:, full_index]):
        eigenvalues, eigenvectors = np.linalg.eigh((gram + gram.T) / 2)
        projected = (eigenvectors * np.maximum(eigenvalues, 0)) @ eigenvectors.T
        trace = float(np.trace(projected))
        normalized = projected / trace
        matrix = degree4.multiplier_matrix(
            len(group), multiplier, degree_six_orbits, degree_six_sizes
        )
        degree4_grams.append(normalized)
        degree4_columns.append(
            np.asarray(matrix @ degree4.pair_vector(normalized)).ravel()
        )
    fixed_matrix = sparse.csr_array(np.column_stack(degree4_columns))

    active_reduced = [
        matrix for matrix, basis in zip(reduced_matrices, bases) if basis.shape[1]
    ]
    coefficient = sparse.hstack([fixed_matrix] + active_reduced, format="csr")
    fixed_weights = cp.Variable(len(degree4_columns), nonneg=True)
    expressions = [fixed_weights] + [
        expression
        for expression in z_coordinate_expressions
        if expression is not None
    ]
    all_values = cp.hstack(expressions)
    margin = cp.Variable()
    problem = cp.Problem(
        cp.Maximize(margin), [coefficient @ all_values + margin <= target]
    )
    print(
        f"SDP coordinates={coefficient.shape[1]} coefficient-nnz={coefficient.nnz}",
        flush=True,
    )
    result = problem.solve(
        solver=cp.SCS,
        verbose=True,
        eps=args.eps,
        max_iters=args.max_iters,
        acceleration_lookback=20,
        use_indirect=not args.direct,
    )
    print("status", problem.status, flush=True)
    print("objective", result, flush=True)
    if fixed_weights.value is None or any(
        variable is not None and variable.value is None for variable in z_variables
    ):
        raise SystemExit("solver returned no certificate coordinates")

    value_parts = [np.asarray(fixed_weights.value).ravel()]
    value_parts.extend(
        np.asarray([variable.value[i, j] for i, j in upper])
        for variable, upper in zip(z_variables, upper_lists)
        if variable is not None
    )
    residual = target - coefficient @ np.concatenate(value_parts)
    print("minimum residual", float(residual.min()), flush=True)

    factor_blocks = []
    factors = []
    for block, (basis, variable) in enumerate(zip(bases, z_variables)):
        if variable is None:
            continue
        q_matrix = basis @ np.asarray(variable.value) @ basis.T
        eigenvalues, eigenvectors = np.linalg.eigh((q_matrix + q_matrix.T) / 2)
        for value, vector in zip(eigenvalues, eigenvectors.T):
            if value > 1e-12:
                factor_blocks.append(block)
                factors.append(np.sqrt(value) * vector)
    degree4_factor_blocks = []
    degree4_factors = []
    for block, (weight, gram) in enumerate(
        zip(np.asarray(fixed_weights.value), degree4_grams)
    ):
        if weight <= 1e-12:
            continue
        eigenvalues, eigenvectors = np.linalg.eigh(weight * gram)
        for value, vector in zip(eigenvalues, eigenvectors.T):
            if value > 1e-12:
                degree4_factor_blocks.append(block)
                degree4_factors.append(np.sqrt(value) * vector)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        args.output,
        allowed=np.asarray(base.ALLOWED, dtype=np.int8),
        group=group,
        multipliers=multipliers,
        m2=base.M2,
        target=target,
        residual=np.asarray(residual),
        margin=np.asarray(float(margin.value)),
        factor_blocks=np.asarray(factor_blocks, dtype=np.int16),
        factors=np.asarray(factors, dtype=float),
        degree4_multipliers=degree4_multipliers,
        degree4_factor_blocks=np.asarray(degree4_factor_blocks, dtype=np.int16),
        degree4_factors=np.asarray(degree4_factors, dtype=float),
    )
    print("quadratic factors", len(factors), flush=True)
    print("degree-four factors", len(degree4_factors), flush=True)
    print(args.output, flush=True)


if __name__ == "__main__":
    main()
